DROP TABLE IF EXISTS status ;
CREATE TABLE status (
  code CHAR(3) NOT NULL,
  name VARCHAR(45) NOT NULL,
  PRIMARY KEY (code),
  UNIQUE INDEX code_UNIQUE (code ASC),
  UNIQUE INDEX name_UNIQUE (name ASC));

DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC),
  UNIQUE INDEX email_UNIQUE (email ASC));

DROP TABLE IF EXISTS login;
CREATE TABLE login (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  logged_in TIMESTAMP NOT NULL);

DROP TABLE IF EXISTS offerset;
CREATE TABLE offerset (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(45) NOT NULL DEFAULT 'unnamed',
  status_code VARCHAR(45) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX offerset_id_UNIQUE (id ASC));

DROP TABLE IF EXISTS offer;
CREATE TABLE offer (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  offerset_id INT UNSIGNED NOT NULL,
  target_class VARCHAR(45) NOT NULL,
  content_class VARCHAR(45) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX offer_id_UNIQUE (id ASC));

DROP TABLE IF EXISTS offer_log;
CREATE TABLE offer_log (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  offerset_id INT NOT NULL,
  offer_id INT NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX offer_log_id_UNIQUE (id ASC));
